-- AMPass Migration 006: Add app_account and remote_desktop vault item types
-- THIS FILE IS INTENTIONALLY EMPTY.
-- The actual migration logic is in 006_app_accounts_remote_desktop.php
-- because it requires conditional checks (INFORMATION_SCHEMA) that cannot
-- be done safely with PDO::exec() in pure SQL (DELIMITER is a mysql CLI
-- command, not supported by PDO).
--
-- The migration runner will execute the .php file instead of this .sql file.
-- If the .sql was already marked as applied, the .php will be skipped.
