<?php
/**
 * AMPass - Two-Factor Authentication (2FA) View
 */
$csrfToken = $csrfToken ?? CSRF::generateToken();
$error = Session::flash('error');
$success = Session::flash('success');
?>

<div class="page-header">
    <a href="<?= APP_URL ?>/settings" class="btn-back">
        <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="19" y1="12" x2="5" y2="12"/><polyline points="12 19 5 12 12 5"/></svg>
        Back
    </a>
    <h1 class="page-title">Two-Factor Authentication</h1>
</div>

<?php if ($error): ?><div class="alert alert-error"><?= $error ?></div><?php endif; ?>
<?php if ($success): ?><div class="alert alert-success"><?= htmlspecialchars($success) ?></div><?php endif; ?>

<div class="settings-grid" style="grid-template-columns: 1fr; max-width: 650px;">
    
    <?php if (!$user['two_factor_enabled']): ?>
    <!-- 2FA SETUP -->
    <div class="card">
        <div class="card-header">
            <h2 class="card-title">Setup Google Authenticator</h2>
            <p class="text-muted" style="font-size: 0.85rem; margin-top: 4px;">Protect your account with an additional layer of security using time-based one-time passwords (TOTP).</p>
        </div>
        <div class="card-body">
            <div style="display: flex; flex-direction: column; gap: 24px;">
                
                <div style="display: flex; align-items: flex-start; gap: 16px;">
                    <div style="background: rgba(99, 102, 241, 0.1); color: #6366f1; width: 36px; height: 36px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 600; flex-shrink: 0;">1</div>
                    <div>
                        <h3 style="font-size: 1rem; font-weight: 600; margin-bottom: 6px;">Scan the QR Code</h3>
                        <p class="text-muted" style="font-size: 0.88rem; line-height: 1.4; margin-bottom: 14px;">Open your Google Authenticator or any TOTP compatible app, tap the '+' icon, and scan this QR code.</p>
                        
                        <div style="background: white; padding: 12px; border-radius: 12px; width: 224px; border: 1px solid var(--border-color); box-shadow: 0 4px 12px rgba(0,0,0,0.05); margin-bottom: 14px;">
                            <img src="https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=<?= urlencode($qrCodeUrl) ?>" alt="2FA QR Code" style="width:200px; height:200px; display:block;">
                        </div>
                        
                        <p class="text-muted" style="font-size: 0.8rem; margin-bottom: 6px;">Or enter this secret key manually into your app:</p>
                        <code style="display: inline-block; background: var(--bg-hover); color: var(--text-color); padding: 8px 12px; border-radius: 6px; font-family: monospace; font-size: 0.95rem; font-weight: 600; border: 1px solid var(--border-color); letter-spacing: 1px;"><?= chunk_split($secret, 4, ' ') ?></code>
                    </div>
                </div>

                <hr style="border: 0; border-top: 1px solid var(--border-color); margin: 0;">

                <div style="display: flex; align-items: flex-start; gap: 16px;">
                    <div style="background: rgba(99, 102, 241, 0.1); color: #6366f1; width: 36px; height: 36px; border-radius: 50%; display: flex; align-items: center; justify-content: center; font-weight: 600; flex-shrink: 0;">2</div>
                    <div style="flex-grow: 1;">
                        <h3 style="font-size: 1rem; font-weight: 600; margin-bottom: 6px;">Verify & Enable</h3>
                        <p class="text-muted" style="font-size: 0.88rem; line-height: 1.4; margin-bottom: 14px;">Enter the 6-digit code generated by your Authenticator app to confirm the setup.</p>
                        
                        <form method="POST" action="<?= APP_URL ?>/settings/enableTwoFactor" style="max-width: 320px;">
                            <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
                            
                            <div class="form-group" style="margin-bottom: 16px;">
                                <label class="form-label">Verification Code</label>
                                <input type="text" name="code" class="form-input" placeholder="e.g. 123456" pattern="[0-9]{3}\s?[0-9]{3}" required autocomplete="one-time-code" maxlength="7" autofocus style="letter-spacing: 2px; font-size: 1.1rem; text-align: center; font-weight: 600;">
                            </div>
                            
                            <button type="submit" class="btn btn-primary btn-full">Enable 2FA</button>
                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
    
    <?php else: ?>
    <!-- 2FA CONFIGURATION & OPTIONS -->
    <div class="card">
        <div class="card-header" style="border-bottom: 1px solid var(--border-color); padding-bottom: 16px;">
            <div style="display: flex; align-items: center; gap: 10px;">
                <span style="display: inline-flex; align-items: center; justify-content: center; background: #e2fbf0; color: #16a34a; width: 24px; height: 24px; border-radius: 50%;">✓</span>
                <h2 class="card-title" style="color: #16a34a;">Google Authenticator 2FA is Active</h2>
            </div>
        </div>
        <div class="card-body" style="padding-top: 20px;">
            <form method="POST" action="<?= APP_URL ?>/settings/updateTwoFactorOptions">
                <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
                
                <h3 style="font-size: 0.95rem; font-weight: 600; margin-bottom: 12px;">Trigger Conditions</h3>
                <p class="text-muted" style="font-size: 0.85rem; line-height: 1.4; margin-bottom: 18px;">Customize when Google Authenticator verification is required. If neither condition is selected, 2FA will be required on every login attempt.</p>
                
                <div class="form-group" style="margin-bottom: 18px;">
                    <label class="check-label" style="display: flex; align-items: flex-start; gap: 10px; cursor: pointer;">
                        <input type="checkbox" name="two_factor_new_device" value="1" <?= $user['two_factor_new_device'] ? 'checked' : '' ?> style="margin-top: 3px;">
                        <div>
                            <span style="font-weight: 500; display: block; font-size: 0.9rem;">Require 2FA only for new/untrusted devices</span>
                            <span class="text-muted" style="font-size: 0.8rem; display: block; margin-top: 2px;">Known/trusted devices will bypass Google Authenticator. Admin logins will always require 2FA on untrusted devices.</span>
                        </div>
                    </label>
                </div>
                
                <div class="form-group" style="margin-bottom: 24px;">
                    <label class="check-label" style="display: flex; align-items: flex-start; gap: 10px; cursor: pointer;">
                        <input type="checkbox" name="two_factor_failed_logins" value="1" <?= $user['two_factor_failed_logins'] ? 'checked' : '' ?> style="margin-top: 3px;">
                        <div>
                            <span style="font-weight: 500; display: block; font-size: 0.9rem;">Trigger 2FA after 10 failed login attempts</span>
                            <span class="text-muted" style="font-size: 0.8rem; display: block; margin-top: 2px;">Require Google Authenticator verification on the next login attempt if there are 10 or more failed login attempts registered in the last 24 hours.</span>
                        </div>
                    </label>
                </div>
                
                <button type="submit" class="btn btn-primary">Save Settings</button>
            </form>
        </div>
    </div>

    <!-- DISABLE 2FA -->
    <div class="card" style="border: 1px solid #fee2e2;">
        <div class="card-header" style="background: #fff5f5; border-bottom: 1px solid #fee2e2;">
            <h2 class="card-title" style="color: #dc2626;">Disable Two-Factor Authentication</h2>
        </div>
        <div class="card-body">
            <p class="text-muted" style="font-size: 0.85rem; line-height: 1.4; margin-bottom: 18px;">Disabling 2FA reduces your account security. You will need your current 2FA Authenticator code to disable it.</p>
            
            <form method="POST" action="<?= APP_URL ?>/settings/disableTwoFactor" style="max-width: 320px;">
                <input type="hidden" name="csrf_token" value="<?= $csrfToken ?>">
                
                <div class="form-group" style="margin-bottom: 16px;">
                    <label class="form-label">Authenticator Code</label>
                    <input type="text" name="code" class="form-input" placeholder="e.g. 123456" required autocomplete="one-time-code" maxlength="6" style="text-align: center; font-weight: 600; font-size: 1.1rem; letter-spacing: 2px;">
                </div>
                
                <button type="submit" class="btn btn-danger">Disable 2FA</button>
            </form>
        </div>
    </div>
    <?php endif; ?>

</div>
