<?php
/**
 * AMPass — Version Information
 * 
 * This file is auto-generated by scripts/sync-version.php
 * Source: GitHub commit count on main branch.
 * Display format: V1.{commit_count}
 * Semver format: 1.{commit_count}.0
 * 
 * Do NOT edit manually — run: php scripts/sync-version.php
 */

define('AMPASS_VERSION_MAJOR', 1);
define('AMPASS_COMMIT_COUNT', 107);
define('AMPASS_VERSION_DISPLAY', 'V1.107');
define('AMPASS_VERSION_SEMVER', '1.107.0');
define('AMPASS_COMMIT_SHA', 'de691bb191735a56cc437a92f93a29be3edd0055');
define('AMPASS_VERSION_UPDATED_AT', '2026-06-03T09:24:42.239757');

// Map to legacy APP_VERSION constant if not already defined
if (!defined('APP_VERSION')) {
    define('APP_VERSION', AMPASS_VERSION_SEMVER);
}
if (!defined('APP_VERSION_DISPLAY')) {
    define('APP_VERSION_DISPLAY', AMPASS_VERSION_DISPLAY);
}
