<?php
/**
 * AMPass — Version Information
 * 
 * This file is auto-generated by scripts/sync-version.php
 * Source: GitHub commit count on main branch.
 * Display format: V1.{commit_count % 100} (padded to 2 digits)
 * Semver format: 1.{commit_count}.0
 * 
 * Do NOT edit manually — run: php scripts/sync-version.php
 */

define('AMPASS_VERSION_MAJOR', 1);
define('AMPASS_COMMIT_COUNT', 102);
define('AMPASS_VERSION_DISPLAY', 'V1.02');
define('AMPASS_VERSION_SEMVER', '1.102.0');
define('AMPASS_COMMIT_SHA', '91a8f455e40ffefc58387684963123b35d216c97');
define('AMPASS_VERSION_UPDATED_AT', '2026-06-03T00:24:47.433451');

// Map to legacy APP_VERSION constant if not already defined
if (!defined('APP_VERSION')) {
    define('APP_VERSION', AMPASS_VERSION_SEMVER);
}
if (!defined('APP_VERSION_DISPLAY')) {
    define('APP_VERSION_DISPLAY', AMPASS_VERSION_DISPLAY);
}
