/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnlockRouteImport } from './routes/unlock'
import { Route as SharedRouteImport } from './routes/shared'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as OfflineRouteImport } from './routes/offline'
import { Route as GeneratorRouteImport } from './routes/generator'
import { Route as FoldersRouteImport } from './routes/folders'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BackupRouteImport } from './routes/backup'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VaultIndexRouteImport } from './routes/vault.index'
import { Route as VaultNewRouteImport } from './routes/vault.new'
import { Route as VaultIdRouteImport } from './routes/vault.$id'

const UnlockRoute = UnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const SharedRoute = SharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const OfflineRoute = OfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => rootRouteImport,
} as any)
const GeneratorRoute = GeneratorRouteImport.update({
  id: '/generator',
  path: '/generator',
  getParentRoute: () => rootRouteImport,
} as any)
const FoldersRoute = FoldersRouteImport.update({
  id: '/folders',
  path: '/folders',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BackupRoute = BackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIndexRoute = VaultIndexRouteImport.update({
  id: '/vault/',
  path: '/vault/',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultNewRoute = VaultNewRouteImport.update({
  id: '/vault/new',
  path: '/vault/new',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultIdRoute = VaultIdRouteImport.update({
  id: '/vault/$id',
  path: '/vault/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/folders': typeof FoldersRoute
  '/generator': typeof GeneratorRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/unlock': typeof UnlockRoute
  '/vault/$id': typeof VaultIdRoute
  '/vault/new': typeof VaultNewRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/folders': typeof FoldersRoute
  '/generator': typeof GeneratorRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/unlock': typeof UnlockRoute
  '/vault/$id': typeof VaultIdRoute
  '/vault/new': typeof VaultNewRoute
  '/vault': typeof VaultIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/audit': typeof AuditRoute
  '/auth': typeof AuthRoute
  '/backup': typeof BackupRoute
  '/dashboard': typeof DashboardRoute
  '/folders': typeof FoldersRoute
  '/generator': typeof GeneratorRoute
  '/offline': typeof OfflineRoute
  '/settings': typeof SettingsRoute
  '/shared': typeof SharedRoute
  '/unlock': typeof UnlockRoute
  '/vault/$id': typeof VaultIdRoute
  '/vault/new': typeof VaultNewRoute
  '/vault/': typeof VaultIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/audit'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/folders'
    | '/generator'
    | '/offline'
    | '/settings'
    | '/shared'
    | '/unlock'
    | '/vault/$id'
    | '/vault/new'
    | '/vault/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/audit'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/folders'
    | '/generator'
    | '/offline'
    | '/settings'
    | '/shared'
    | '/unlock'
    | '/vault/$id'
    | '/vault/new'
    | '/vault'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/audit'
    | '/auth'
    | '/backup'
    | '/dashboard'
    | '/folders'
    | '/generator'
    | '/offline'
    | '/settings'
    | '/shared'
    | '/unlock'
    | '/vault/$id'
    | '/vault/new'
    | '/vault/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AuditRoute: typeof AuditRoute
  AuthRoute: typeof AuthRoute
  BackupRoute: typeof BackupRoute
  DashboardRoute: typeof DashboardRoute
  FoldersRoute: typeof FoldersRoute
  GeneratorRoute: typeof GeneratorRoute
  OfflineRoute: typeof OfflineRoute
  SettingsRoute: typeof SettingsRoute
  SharedRoute: typeof SharedRoute
  UnlockRoute: typeof UnlockRoute
  VaultIdRoute: typeof VaultIdRoute
  VaultNewRoute: typeof VaultNewRoute
  VaultIndexRoute: typeof VaultIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unlock': {
      id: '/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof UnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shared': {
      id: '/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof SharedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offline': {
      id: '/offline'
      path: '/offline'
      fullPath: '/offline'
      preLoaderRoute: typeof OfflineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/generator': {
      id: '/generator'
      path: '/generator'
      fullPath: '/generator'
      preLoaderRoute: typeof GeneratorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/folders': {
      id: '/folders'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof FoldersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backup': {
      id: '/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof BackupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/': {
      id: '/vault/'
      path: '/vault'
      fullPath: '/vault/'
      preLoaderRoute: typeof VaultIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/new': {
      id: '/vault/new'
      path: '/vault/new'
      fullPath: '/vault/new'
      preLoaderRoute: typeof VaultNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault/$id': {
      id: '/vault/$id'
      path: '/vault/$id'
      fullPath: '/vault/$id'
      preLoaderRoute: typeof VaultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AuditRoute: AuditRoute,
  AuthRoute: AuthRoute,
  BackupRoute: BackupRoute,
  DashboardRoute: DashboardRoute,
  FoldersRoute: FoldersRoute,
  GeneratorRoute: GeneratorRoute,
  OfflineRoute: OfflineRoute,
  SettingsRoute: SettingsRoute,
  SharedRoute: SharedRoute,
  UnlockRoute: UnlockRoute,
  VaultIdRoute: VaultIdRoute,
  VaultNewRoute: VaultNewRoute,
  VaultIndexRoute: VaultIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
